### ISSUE TITLE
Doc on connecting a judge

### ISSUE THREAD

**Issue by Xyene** [DMOJ/docs#38]

**Comment by kaijianwang** [comment]
Hi @Xyene ,

I'm a newbee to DMOJ who failed to connect judge and site. After installing site and judge, I found there is no documentation on connecting judge to the site server.

I'm always get error messages as follows after trying `dmoj -c config.yml <sitehostname>` at the judge machine:
`INFO 2018-04-24 23:23:39,416 12046 packet Opening connection to: [oj]:9999
ERROR 2018-04-24 23:23:39,489 12046 packet Connection failed due to socket error: [oj]:9999
Traceback (most recent call last):
  File "/home/judge/judge/dmoj/packet.py", line 120, in _do_reconnect
    self._connect()
  File "/home/judge/judge/dmoj/packet.py", line 84, in _connect
    self.conn = socket.create_connection((self.host, self.port), timeout=5)
  File "/usr/lib/python2.7/socket.py", line 571, in create_connection
    raise err
error: [Errno 111] Connection refused
`.

The site server is running at another machine which could successfully accept user registration and I'd created a judge through admin site with the same name and key in judge configuration file.

**Hence, I'm wondering if any DMOJ member could provide a brief documentation of major steps in judge connection process.**

Looking forward for your reply!

Thanks!

**Comment by Xyene** [comment]
Make sure the bridge is running (`python manage.py runbridged` on the site server) and that the port the bridge listens on ([`BRIDGED_JUDGE_ADDRESS`](https://github.com/DMOJ/site/blob/2f627ef6a00001ab2e1d783147dfab15bf996376/dmoj/settings.py#L310)) is exposed through your firewall.
